models/FileProcessor.php
<?php

namespace app\models;


use Keboola\Csv\CsvReader;
use Keboola\Csv\CsvWriter;
use Keboola\Csv\Exception;

class FileProcessor
{
    protected $source;
    /**
     * @var ProcessorInterface[]
     */
    protected $rowProcessors = [];
    /**
     * @var CsvReader
     */
    protected $reader;
    /**
     * @var CsvWriter
     */
    protected $writer;
    protected $destination;

    public function __construct($sourceCsvFile)
    {
        $this->source = $sourceCsvFile;
    }

    /**
     * @param ProcessorInterface[] $processors
     */
    public function setProcessors($processors)
    {
        $this->rowProcessors = $processors;
    }

    public function write($destinationCsvFile)
    {
        $this->destination = $destinationCsvFile;

        $this->reader = new CsvReader($this->source,
            ';',
            CsvReader::DEFAULT_ENCLOSURE,
            CsvReader::DEFAULT_ESCAPED_BY,
            1
        );
        $this->writer = new CsvWriter($this->destination, ';');
        $this->writer->writeRow($this->reader->getHeader());

        foreach ($this->reader as $row) {
            try {
                $this->writer->writeRow(
                    $this->processRow($row)
                );
            } catch (Exception $exception) {
                \Yii::error($exception->getMessage());
            }
        }
    }

    protected function processRow($row)
    {
        $output = $row;
        foreach ($this->rowProcessors as $processor) {
            $output = $processor->process($output);
        }
        return $output;
    }
}

models/ProcessorInterface.php
<?php

namespace app\models;


interface ProcessorInterface
{
    /**
     * @param array $row
     * @return array
     */
    public function process($row);
}

models/RowPriceProcessor.php
<?php

namespace app\models;


use yii\base\Model;

class RowPriceProcessor extends Model implements ProcessorInterface
{
    public $increasePercent = 0.0;

    public function process($row)
    {
        $output = $row;
        $price = floatval($row[4]);
        $newPrice = round($price + $price * ($this->increasePercent / 100), 2);
        $output[4] = $newPrice;
        return $output;
    }


}

models/UploadForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

class UploadForm extends Model
{
    public $increasePercent = 0.0;

    public $csvFile;
    public $filePath = null;
    public $fileName = null;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [

            [['csvFile'], 'required'],
            //[['csvFile'], 'file', 'skipOnEmpty' => false, 'extensions' => 'csv'],

            ['increasePercent', 'number'],

        ];
    }

    /**
     * @return array customized attribute labels
     */
    public function attributeLabels()
    {
        return [
            'increasePercent' => 'Процент увеличения цен',
            'csvFile' => 'Файл CSV',
        ];
    }

    public function upload()
    {

        if ($this->validate()) {
            $csvFile = UploadedFile::getInstance($this, 'csvFile');
            $directory = Yii::getAlias('@uploads') . DIRECTORY_SEPARATOR;

            if (!is_dir($directory)) {
                FileHelper::createDirectory($directory);
            }

            if ($csvFile) {
                $uid = str_replace('.', '', uniqid(time(), true));
                $fileName = $uid . '.' . $csvFile->extension;
                $filePath = $directory . $fileName;
                if ($csvFile->saveAs($filePath)) {
                    $this->filePath = $filePath;
                    $this->fileName = $fileName;
                    return true;
                }
            }
        }
        var_dump($this->errors);
        return false;
    }

}

controllers/ProcessController.php
<?php

namespace app\controllers;

use app\models\UploadForm;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class ProcessController extends Controller
{
    public function actionResult($fileName)
    {

        $directory = Yii::getAlias('@downloads') . DIRECTORY_SEPARATOR;
        $filePath = $directory . $fileName;

        $source = Yii::getAlias('@downloads') . DIRECTORY_SEPARATOR . $fileName;

        $param = file_exists($filePath) ? [
            'exist' => true,
            'url' => Yii::getAlias('@webDownloads') . DIRECTORY_SEPARATOR . $fileName,
        ] : [
            'exist' => false,
            'source' => file_exists($source),
            'url' => null,
        ];

        return $this->render('result', $param);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $model = new UploadForm();

        if (Yii::$app->request->isPost) {

            if ($model->load(Yii::$app->request->post())) {

                $clearCmd = 'cd ' . Yii::getAlias('@app') . DIRECTORY_SEPARATOR . "&& php yii process/clear";
                exec($clearCmd);

                $model->csvFile = UploadedFile::getInstance($model, 'csvFile');
                if ($model->upload()) {
                    // file is uploaded successfully
                    $source = $model->filePath;
                    $destination = Yii::getAlias('@downloads') . DIRECTORY_SEPARATOR . $model->fileName;
                    $processCmd = 'cd ' . Yii::getAlias('@app') . DIRECTORY_SEPARATOR . "&& php yii process {$source} {$destination} {$model->increasePercent} &";
                    exec($processCmd);
                    sleep(2);
                    return $this->redirect(['result', 'fileName' => $model->fileName]);
                }
            } else {
                return $this->render('index', [
                    'model' => $model,
                ]);
            }


        }
        return $this->render('index', [
            'model' => $model,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'PriceRewriter',//Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            //['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Загрузить', 'url' => ['/process/index']],
            //['label' => 'Contact', 'url' => ['/site/contact']],
//            Yii::$app->user->isGuest ? (
//                ['label' => 'Login', 'url' => ['/site/login']]
//            ) : (
//                '<li>'
//                . Html::beginForm(['/site/logout'], 'post')
//                . Html::submitButton(
//                    'Logout (' . Yii::$app->user->identity->username . ')',
//                    ['class' => 'btn btn-link logout']
//                )
//                . Html::endForm()
//                . '</li>'
//            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; RF <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/process/index.php
<?php

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\UploadForm */

$this->title = 'Обработка файла';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="upload-form container">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'],
        'id' => 'upload-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-3 control-label'],
        ],
    ]); ?>

    <div class="form-group">
        <?= $form->field($model, 'csvFile')->fileInput(['accept' => '.csv']) ?>
    </div>

    <div class="form-group">
        <?= $form->field($model, 'increasePercent')->textInput(['autofocus' => true]) ?>
    </div>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Обработать', ['class' => 'btn btn-primary', 'name' => 'process-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/process/result.php
<?php

use yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var bool $exist */
/* @var bool $source */
/* @var string $url */

$this->title = 'Результат обработки файла';

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="container">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if ($exist): ?>
        <p>
            Обработка файла завершена.
        </p>

        <?= Html::a('Скачать', $url, ['class' => 'btn btn-primary']); ?>

    <?php else: ?>

        <?php if ($source): ?>
        <p>
            Обработка файла в процессе.
        </p>
        <p>
            Подождите и обновите страницу для получения ссылки на файл.
        </p>
            <?= Html::a('Обновить', 'javascript:history.go(0)', ['class' => 'btn btn-warning']); ?>

        <?php else: ?>

            <p>
                Файл источник отсуствует.
            </p>
            <p>
                Обработанный файл отсуствует.
            </p>
            <p>
                Попробуйсте загрузить файл снова.
            </p>
            <?= Html::a('Загрузить', '/', ['class' => 'btn btn-danger']); ?>
        <?php endif; ?>

    <?php endif; ?>
</div>